Task getters
mindera-school/MS5-To-Do-List pull request #110
Opened 2023-03-21 17:29 UTC by Rocha1313

### Descrição

Neste PR abordei o ticket completo dos GETS das Tasks

Nele esta incluido

> 1. O GET das previews
> 2. O GET dos detalhes da Task
> 3. O GET das SubTasks

### Imagem

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/62727949/226692382-44158a98-1d55-446b-8902-612127f1a642.png">

### Referência para a Issue do Jira

[Link para o Jira](https://tdlflavio.atlassian.net/jira/software/projects/TODO/boards/2?selectedIssue=TODO-52
)
### Testes

- [ ] Sim, eu testei as alterações e elas funcionam corretamente.
- [ ] Não, eu não testei as alterações.

### Documentação (WIKI)

- [ ] Sim, eu atualizei a documentação conforme necessário.
- [ ] Não, a documentação não precisa ser atualizada.

### Checklist

Antes de enviar esta solicitação pull, verifique se o seguinte foi concluído:

- [ ] [Meus commits seguem as convenções do projeto](https://gist.github.com/tonibardina/9290fbc7d605b4f86919426e614fe692).
- [ ] Meu código faz sentido com o design.
- [ ] Eu atualizei os testes para corresponder às minhas alterações.

2023-03-21 19:12 UTC, LeoHabs approved these changes
Parece me tudo fixe

2023-03-21 19:12 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
> +            throw new InvalidUserException("Invalid user");
N dá para para meter logo essa string default nas exceções?

2023-03-22 11:11 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TasksRepository.java
> +
espaço a mais

2023-03-22 11:11 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOTaskDetails.java
> +
espaço 
```suggestion
```

2023-03-22 11:44 UTC, Adan0k requested changes

2023-03-22 11:44 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
> +        }
isso me parece mal
```suggestion
        List<TasksEntity> tasks = user.get().getTasks();
```

2023-03-22 11:44 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
> +        });
acho que tu pode fazer isso só numa linha
```suggestion
        tasks.get().forEach(task -> {
            dtos.add(Converter.toDTOTaskPreview(task));
        });
```

2023-03-22 11:44 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
> +        }
dá pra pegar essas `tasks` pelo o usersRepository como eu falei no outro comentário

2023-03-22 11:44 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
> +    public ResponseEntity<DTOTaskDetails> getTaskDetails(Integer taskId, Integer userId){
por algum motivo, quando o `taskId` é diferente do `userId` dá `bad request`

2023-03-22 11:44 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
> +        });
o que isso deveria fazer?

2023-03-22 14:11 UTC, Adan0k approved these changes

2023-03-22 14:11 UTC, merged