Add tags
mindera-school/MS5-To-Do-List pull request #165
Opened 2023-04-06 11:18 UTC by Gabriel-Sous-a

### Descrição

Adicionar tags

### Imagem

[Se aplicável, incluir uma imagem/gif para ajudar a ilustrar as mudanças.]

### Referência para a Issue do Jira

[Adicionar o link para a issue do Jira]

### Testes

- [ ] Sim, eu testei as alterações e elas funcionam corretamente.
- [ ] Não, eu não testei as alterações.
- [ ] Não aplicavel.

### Documentação (WIKI)

- [ ] Sim, eu atualizei a documentação conforme necessário.
- [ ] Não, a documentação não precisa ser atualizada.
- [ ] Não aplicavel.

### Checklist

Antes de enviar esta solicitação pull, verifique se o seguinte foi concluído:

- [ ] [Meus commits seguem as convenções do projeto](https://gist.github.com/tonibardina/9290fbc7d605b4f86919426e614fe692).
- [ ] Meu código faz sentido com o design.
- [ ] Eu atualizei os testes para corresponder às minhas alterações.

2023-04-06 14:29 UTC, LeoHabs requested changes
Tem q se mudar para o add tag só aparecer no modo edit se n é super confuso. Eu fiquei a carregar a achar q n tava a funcionar o botao. Ou ent ao carregar no botão de adicionar ele ativar o modo edição

2023-04-06 15:17 UTC, Rocha1313 approved these changes
Por mim pode ir, nao vi nada de suspeito

2023-04-07 09:35 UTC, LeoHabs approved these changes

2023-04-07 10:26 UTC, Adan0k approved these changes

2023-04-07 10:38 UTC, merged