fix bug to first use of app
mindera-school/MS5-To-Do-List pull request #174
Opened 2023-04-09 19:57 UTC by LeoHabs

### Descrição

Correção de bug que partia a app na primeira utilização em guest mode.

### Testes

- [x] Sim, eu testei as alterações e elas funcionam corretamente.
- [ ] Não, eu não testei as alterações.
- [ ] Não aplicavel.

### Documentação (WIKI)

- [ ] Sim, eu atualizei a documentação conforme necessário.
- [ ] Não, a documentação não precisa ser atualizada.
- [x] Não aplicavel.

### Checklist

Antes de enviar esta solicitação pull, verifique se o seguinte foi concluído:

- [x] [Meus commits seguem as convenções do projeto](https://gist.github.com/tonibardina/9290fbc7d605b4f86919426e614fe692).
- [ ] Meu código faz sentido com o design.
- [ ] Eu atualizei os testes para corresponder às minhas alterações.

2023-04-09 19:58 UTC, Gabriel-Sous-a approved these changes

2023-04-10 08:24 UTC, Rocha1313 approved these changes

2023-04-10 08:25 UTC, Gabriel-Sous-a requested changes

2023-04-10 08:25 UTC, Gabriel-Sous-a commented on FE/src/App.js
> +import LeftMenu from "./components/LeftMenu";
Isto esta a dar erro, tas a importar 2 vezes a mesma coisa

2023-04-10 08:38 UTC, Gabriel-Sous-a approved these changes

2023-04-10 08:56 UTC, merged