Add: All DTOs
mindera-school/MS5-To-Do-List pull request #60
Opened 2023-02-25 21:47 UTC by Adan0k

2023-02-26 10:21 UTC, LeoHabs requested changes
Acho que há cenas aqui que já não serão necessarias. Visto que agora já não vão haver followers, basta só os comments. Tipo deixem ficar que já está feito e dps no futuro até se pode integrar isso, digo isto só mais para não perderem muito tempo com o que tenha a ver com comments, followers e assim

2023-02-26 10:21 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOGroup.java
> +    private Integer id;
Acho que devias ter o descritivo do id tipo groupId

2023-02-26 10:21 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOLoggedUser.java
> +    private String fistName;
first*

2023-02-26 10:21 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOLoggedUser.java
> +    private Integer id;
n deverias por userId só para ficar mais organizadinho?

2023-02-27 14:30 UTC, LeoHabs approved these changes

2023-02-27 17:15 UTC, Rocha1313 submitted a review, later dismissed

2023-02-28 10:11 UTC, Rocha1313 approved these changes
Looks nice

2023-02-28 10:12 UTC, merged