58 create database entities
mindera-school/MS5-To-Do-List pull request #80
Opened 2023-03-01 17:00 UTC by Rocha1313

_Estas são todas a entities da base de dados_

### Base de dados

<img width="991" alt="Screenshot 2023-03-01 at 16 56 20" src="https://user-images.githubusercontent.com/62727949/222208573-47863715-c0a0-4c98-a579-0f58ed65f94c.png">

Podem dar uma vista de olhos a base de dados caso seja mais fácil

- [ ]  Marcar para caso goste desta forma de PR description

2023-03-03 10:08 UTC, Adan0k approved these changes

2023-03-03 10:45 UTC, LeoHabs requested changes

2023-03-03 10:45 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/CommentsEntity.java
Mano pff tira estes espaços 😭

2023-03-03 10:45 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/FollowersEntity.java
> +package shcool.mindera.toDoListAPI.entities;
Mano.... shcool?! School

2023-03-03 10:45 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/TagsEntity.java
> +    @Id
Parece conice mas pff tenta ser consistente com os espaços

2023-03-03 10:45 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/UserRepository.java
> +public class UserRepository {
Mete já o extends JPARepo e transforma para interface 
```suggestion
public interface UserRepository  extends  JpaRepository<T,T>{
```

2023-03-03 10:45 UTC, LeoHabs commented on BE/toDoListAPI/src/main/resources/application.yml
>      url: jdbc:${TYPE}://${HOST}:${PORT}/${NAME}
Gosto

2023-03-03 10:45 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/UserRepository.java
> +public class UserRepository {
Depois não será necessário ter mais que um Repo?

2023-03-03 11:14 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/CommentsEntity.java
Não acho isso certo, vais estar a dar import a tudo quando nao é necessario a class vai ficar mais pesada

2023-03-03 11:15 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/TagsEntity.java
> +    @Id
No intellij nao fica, mas se quiseres deixo assim

2023-03-03 11:16 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/UserRepository.java
> +public class UserRepository {
Mano nao te esquecas que isto é um ticket de entidades, isso é so para teste

2023-03-03 11:18 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/UserRepository.java
> +public class UserRepository {
Ainda nao pensei nisso sinceramente, tenho de pesquisar qual vai ser a melhor opçao

2023-03-03 11:29 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/CommentsEntity.java
Ahn? Tava a falar porque no Github aparecem espaços, não dos importes em si, parece me bem isso

2023-03-03 11:30 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/UserRepository.java
> +public class UserRepository {
Mas se já está uma class para teste , porque não deixar a interface que vai estar

2023-03-03 11:31 UTC, LeoHabs approved these changes

2023-03-03 11:32 UTC, Adan0k requested changes

2023-03-03 11:32 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/GroupsRepositoryInterface.java
> +public interface GroupsRepositoryInterface extends JpaRepository<GroupsEntity, Integer> {
GroupsRepositoryInterface parece redundante
```suggestion
public interface GroupsRepository extends JpaRepository<GroupsEntity, Integer> {
```

2023-03-03 11:32 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/entities/CommentsEntity.java
oh esquece fiquei confuso pq nao vi o import em baixo, para a proxima faz um bloco sff

2023-03-03 11:47 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/GroupsRepositoryInterface.java
> +public interface GroupsRepositoryInterface extends JpaRepository<GroupsEntity, Integer> {
Volto a dizer ticket de entidades, no ticket dos repositorios fazemos essas alterações

2023-03-04 12:06 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/GroupsRepositoryInterface.java
> +public interface GroupsRepositoryInterface extends JpaRepository<GroupsEntity, Integer> {
> Volto a dizer ticket de entidades, no ticket dos repositorios fazemos essas alterações

Ticket das entidades certo, mas que criaste os repos ficam já criados direito ne

2023-03-05 12:52 UTC, Adan0k approved these changes

2023-03-05 12:55 UTC, merged