92 tag implementation
mindera-school/MS5-To-Do-List pull request #94
Opened 2023-03-15 15:59 UTC by Adan0k

2023-03-15 19:42 UTC, Rocha1313 requested changes
Podes fazer o favor de eliminar o controller dos grupos neste PR? Não esta lá a fazer nada

2023-03-15 19:42 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TagController.java
>      @PostMapping("new-tag")
```suggestion
    @PostMapping("/new-tag")
```
Ja sabes

2023-03-15 19:42 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOTaskPreview.java
>      private String tagsURL;
Faltou adicionar a `POSITION` e o `URL para a task completa`

2023-03-15 19:42 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
> +    public void associateTask(TasksEntity task, TagsEntity tag){
```suggestion
    }
    
    public void associateTask(TasksEntity task, TagsEntity tag){
```

Ja sabes

2023-03-15 19:42 UTC, Rocha1313 commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
> +       tagsE.forEach(e-> tags.add(new DTOTag(e.getTagId(),e.getName(),e.getColor())));
Ue, usaste aqui

2023-03-15 20:08 UTC, LeoHabs requested changes
Pedir tags de uma task que n existe dá 500. De resto está tudo a funcionar.

2023-03-15 20:10 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
> +        }
Pois pensei o msm, n sei se faz sentido 404 pq no fundo ele encontra, só n tem nada

2023-03-15 20:11 UTC, LeoHabs commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
> +       }
Yah para nós tmb faz mais sentido receber um array vazio. Eu protegi o sistema de injeção de n receber nada mas a questão é a mesma q em cima, a cena existe, só n tem nada

2023-03-15 22:03 UTC, Rocha1313 approved these changes

2023-03-15 22:03 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTONewTag.java
yep

2023-03-15 22:04 UTC, Rocha1313 requested changes
Tinha dado approve sem querer

2023-03-15 22:19 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
> +       }
nesse caso é se a task não existir

2023-03-15 22:20 UTC, Adan0k commented on BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
> +       }
se a task não existir é 400 na mesma

2023-03-16 12:43 UTC, Rocha1313 approved these changes
Parece bem

2023-03-16 13:10 UTC, LeoHabs approved these changes

2023-03-16 13:10 UTC, merged